language: php

php:
  - 5.3
  - 5.4

before_script:
  - pear channel-discover pear.zero.mq
  - pecl install zero.mq/zmq-beta
  - echo "extension=zmq.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script: phpunit --coverage-text
