language: php

php:
  - 5.3
  - 5.4

before_script:
  - pear channel-discover pear.zero.mq
  - pecl install pear.zero.mq/zmq-beta
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script: phpunit --coverage-text
